name: Run_Test_R_Script

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          # This points to the default R library location on Ubuntu runners
          path: /home/runner/work/_temp/Library
          key: ${{ runner.os }}-r-cache-${{ hashFiles('test.R') }}
          restore-keys: ${{ runner.os }}-r-cache-

      - name: Install R packages
        run: |
          install.packages('pak', repos = 'https://r-lib.github.io/p/pak/devel')
          pak::pkg_install(c(
            "janitor", "lubridate", "hms", "tidyr", "stringr", "readr", 
            "forcats", "dplyr", "tibble", "bit64", "purrr", "crayon", 
            "googlesheets4", "httr", "httr2", "rio", "googledrive", 
            "xfun", "xml2", "rvest", "textutils", "urltools", "jsonlite"
          ))
        shell: Rscript {0}

        - name: Check secret exists
        run: |
          if [ -z "$GOOGLE_SHEETS_KEY" ]; then
            echo "SECRET IS EMPTY"
          else
            echo "SECRET LENGTH: ${#GOOGLE_SHEETS_KEY}"
          fi
        env:
          GOOGLE_SHEETS_KEY: ${{ secrets.GOOGLE_SHEETS_KEY }}

      - name: Run Test R Script
        env:
          GOOGLE_SHEETS_KEY: ${{ secrets.GOOGLE_SHEETS_KEY }}
        run: Rscript test.R
